---
- name: Ensure domain_name is downloaded
  get_url:
    url: https://github.com/neonichu/ruby-domain_name/releases/download/v0.5.99999999/domain_name-0.5.99999999.gem
    dest: /tmp/domain_name-0.5.99999999.gem

# Gem module does not pick-up on Ruby manager installations unless shenanigans are made
- name: Ensure domain_name is installed
  shell: $SHELL -lc 'gem install /tmp/domain_name-0.5.99999999.gem'

- name: Ensure xcode-install is installed
  shell: $SHELL -lc 'gem install --conservative xcode-install'
